<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    //personnaliser les requetes pour faire une seule requetes au lieu de deux.
    public function findLatest(){
        return $this->createQueryBuilder('p')
            ->join('p.tags','t')
            ->select('p,t')
            ->getQuery()
            ->getResult();
    }
}
