<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'App\\Controller\\DeleteProduct::__invoke' => array('privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true),
    'App\\Controller\\GetProduct::__invoke' => array('privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true),
    'App\\Controller\\ProductController::__invoke' => array('privates', '.service_locator.S1KoMNJ', 'get_ServiceLocator_S1KoMNJService.php', true),
    'App\\Controller\\PutProduct::__invoke' => array('privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true),
    'App\\Controller\\DeleteProduct:__invoke' => array('privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true),
    'App\\Controller\\DeleteProduct' => array('privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true),
    'App\\Controller\\GetProduct:__invoke' => array('privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true),
    'App\\Controller\\GetProduct' => array('privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true),
    'App\\Controller\\ProductController:__invoke' => array('privates', '.service_locator.S1KoMNJ', 'get_ServiceLocator_S1KoMNJService.php', true),
    'App\\Controller\\ProductController' => array('privates', '.service_locator.S1KoMNJ', 'get_ServiceLocator_S1KoMNJService.php', true),
    'App\\Controller\\PutProduct:__invoke' => array('privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true),
    'App\\Controller\\PutProduct' => array('privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true),
))), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
