<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.oBOgE14' shared service.

return $this->privates['.service_locator.oBOgE14'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'registry' => array('services', 'doctrine', 'getDoctrineService', false),
));
