<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\ProductController' shared autowired service.

include_once $this->targetDirs[3].'/src/Controller/ProductController.php';

return $this->services['App\Controller\ProductController'] = new \App\Controller\ProductController();
